### ISSUE TITLE
Plugin stopped working on Monterey Mac OS

### ISSUE THREAD

**Issue by azakordonets** [citelao/Spotify-for-Alfred#138]
Hello everyone. Thanks for such amazing plugin - I use it on daily basis. However, when I have upgraded my Mac OS to Monterey, the plugin stopped working. It doesn't fetch data from Spotify and just shows empty search bar. I tried to re-import it, but that doesn't help. Any way I can find some debug logs ?

**Comment by natashh** [comment]
I have the same, I just started using Alfred 4 and found the Spotifious. When I import workflow and run Spotifious I do not have option to choose counter, configure etc. Only Spotify searchbar wich is not working.

**Comment by arekmaz** [comment]
for me it was fixed by #132, and after that in the workflow debug mode I was getting `/bin/bash: php not found`, so I manually added `/opt/homebrew/bin` (location of my php installation, by default `/usr/local/bin` was assumed) to all bash workflow scripts, all is good now

**Comment by citelao** [comment]
Thank you everyone for reporting and looking into this!

@arekmaz, I think you found the issue: PHP is no longer available by default in macOS Monterey! I've written a PR that adds a PHP install step to setup: #139.

~~Draft release: https://github.com/citelao/Spotify-for-Alfred/releases/tag/v0.13.10~~
See below, try Draft Release v2: https://github.com/citelao/Spotify-for-Alfred/releases/tag/v0.13.10.1

Please check it out! It should help you install PHP in one step; if that doesn't work, please let me know (I can't really test on my computer, which has PHP installed).

**Comment by azakordonets** [comment]
The new release worked for me ! I tried to debug it before even with PHP installed on my mac and it wasn't working, but 0.13.10 is working like a charm - thanks a lot for such helpful plugin. I was really struggling without it

**Comment by natashh** [comment]
It is still not working for my after PHP installation. I did not get the:
Follow the instructions on the set-up menu.
You'll be asked to choose your country (for better search results— you can opt out).
You'll create a Spotify application (or not, you can opt out).
You'll link the new app to Spotifious.

**Comment by citelao** [comment]
I noticed a typo in my script that broke playback. Please try out this:

Draft release v2: https://github.com/citelao/Spotify-for-Alfred/releases/tag/v0.13.10.1

@natashh, can you give more information? What do you see instead? Does the Alfred debugging log have any useful info?

**Comment by citelao** [comment]
I'm going to leave this open until I merge the change into main.

**Comment by djpowers** [comment]
Just chiming in to note that the v0.13.10.1 update seemed to fix things for me. Thanks! Is that release ready to be merged into main?

**Comment by citelao** [comment]
@djpowers Thanks for the update! I have finally tested it myself on a real machine as of this evening :).

It's been ready for a while, I just hate my release process and never find the time to go through it. Soon™️!
